fun main(args: Array<String>) {
    println("Day1A: ${day1ASolution()}")
    println("Day1B: ${day1BSolution()}")
    println("Day2A: ${day2ASolution()}")
    println("Day2B: ${day2BSolution()}")
    println("Day3A: ${day3ASolution()}")
    println("Day3B: ${day3BSolution()}")
    println("Day4A: ${day4ASolution()}")
    println("Day4B: ${day4BSolution()}")
    println("Day5A: ${day5ASolution()}")
    println("Day5B: ${day5BSolution()}")
    println("Day6A: ${day6ASolution()}")
    println("Day6B: ${day6BSolution()}")
    println("Day7A: ${day7ASolution()}")
    println("Day7B: ${day7BSolution()}")
    println("Day8A: ${day8ASolution()}")
    println("Day8B: ${day8BSolution()}")
    println("Day9A: ${day9ASolution()}")
    println("Day9B: ${day9BSolution()}")
    println("Day10: ${day10ASolution()}")
    println("Day11A: ${day11ASolution()}")
    println("Day11B: ${day11BSolution()}")
    //day12ASolution() //Too slow, see comment with optimization
    println("Day13A: ${day13ASolution()}")
    println("Day13B: ${day13BSolution()}")
    println("Day14A: ${day14ASolution()}")
    println("Day14B: ${day14BSolution()}")
    // Also a little slow
    //println("Day15A: ${day15ASolution()}")
    //println("Day15D: ${day15BSolution()}")
    println("Day16A: ${day16ASolution()}")
    println("Day16B: ${day16BSolution()}")
    //println("Day17A: ${day17ASolution()}")
    //println("Day17B: ${day17BSolution()}")
    println("Day18A: ${day18ASolution()}")
    //println("Day18B: ${day18BSolution()}")
    println("Day19A: ${day19ASolution()}")
//    println("Day19B: ${day19BSolution()}")
    println("Day20A: ${day20ASolution()}")
    println("Day20A: ${day20BSolution()}")
    //   println("Day20A: ${day20BSolution()}")
    println("Day21B: ${day21ASolution()}")
    println("Day22A: ${day22ASolution()}")
    println("Day22B: ${day22BSolution()}")

}